server:
  port: 8848

spring:
  application:
    name: provider-demo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8765/eureka
    register-with-eureka: true
    fetch-registry: false