server:
  port: 8763

spring:
  application:
    name: consumer
#  cloud:
#    config:
#      name: goods
#      profile: dev
#      label: master
#      discovery:
#        enabled: true
#        service-id: config-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: true