server:
  port: 8849

spring:
  application:
    name: consumer-demo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8765/eureka
    register-with-eureka: false
    fetch-registry: true